### ISSUE TITLE
Regarding the request for installation of "MATLAB and Simulink Integration"

### ISSUE THREAD

**Issue by mmuetzel** [gnu-octave/statistics-bootstrap#1]
IIUC, we'd need to link a Mathworks account with a valid MATLAB or Simulink license to be able to activate the App.

Please, let us know if that is something you have and you need help setting that up.

**Comment by acp29** [comment]
Hi @mmuetzel, I use MATLAB through the institutional MATLAB licence at the University of Sussex (UK). I also have a profile on Mathworks and the licence number associated with the aforementioned licence is 40591570. Is this all the info you need? I tried to do it myself but I only have maintainer, not owner status, for this package hosted by gnu-octave. Is is possible to change that since I'm the only person who maintains that package? Or would doing so grant me ownership of other packages at gnu-octave (which you probably don't want me to have).

<img width="1172" alt="image" src="https://github.com/gnu-octave/statistics-resampling/assets/25886889/5a7324fc-b779-4af3-8f5c-14ee56cf8def">

<img width="898" alt="image" src="https://github.com/gnu-octave/statistics-resampling/assets/25886889/8da5abf1-cd06-40f5-afd2-6497c77c2008">

<img width="1206" alt="image" src="https://github.com/gnu-octave/statistics-resampling/assets/25886889/049e4108-c37a-441f-b213-df3e99f437df">

**Comment by acp29** [comment]
The alternative is that I setup a fork of the repo with my own profile, install a GitHub App to automatically keep it synced with the gnu-octave/statistics-resampling package and integrate my synced-fork of the package with the Mathworks FileExchange submission ([52741](https://uk.mathworks.com/matlabcentral/fileexchange/52741-statistics-resampling)). Happy either way. Thank you so much for the quick reply and support on this. I appreciate that making octave/matlab code also available to matlab users goes against the philosophy of some people - I just want to make my contributions as accessible to as many people as possible, whether they use Octave or Matlab. I hope that is ok with you.

**Comment by mmuetzel** [comment]
You should have admin rights for this repository:
<img width="489" alt="image" src="https://github.com/gnu-octave/statistics-resampling/assets/65065102/d5d7d255-07c4-4099-95bb-33ba30da3bf1">

And it looks like the app is installed and enabled for this repository:
<img width="405" alt="image" src="https://github.com/gnu-octave/statistics-resampling/assets/65065102/0f08b7be-7534-43e4-9a27-992267b316d3">

When I clicked on that link initially, I was asked to log in to a MathWorks account with what looked like an email address and password. I didn't do that. So, I don't know if that works.

Please, let me know if I could do something else.

**Comment by acp29** [comment]
Hi @mmuetzel, unfortunately that hasn't worked. I think that logging into Mathworks is the critical step because when I did that for a fork of the repository ([acpennlab/statistics-resampling](https://github.com/acpennlab/statistics-resampling)) that I am 'owner' for, it worked (https://github.com/acpennlab/statistics-resampling). I could go ahead and use that instead but then I will lose all the download stats, comments and stars since I will essentially be creating a [new submission](https://uk.mathworks.com/matlabcentral/fileexchange/157226-statistics-resampling). This would be a shame but it might be the way it goes since when I try to update the integration for [gnu-octave/statistics-resampling](https://github.com/gnu-octave/statistics-resampling/) repo myself logged in under my profile (acp29) I get the message 'This action must be performed by an organization owner'... in other words I think I need to be listed as an owner in the gnu-octave Github account, which I am not currently:
<img width="1193" alt="image" src="https://github.com/gnu-octave/statistics-resampling/assets/25886889/cb25cd90-2b07-43c3-b6bb-aa415c27d60c">

The only way I can think of maintaining [the FileExchange link to the gnu-octave/statistics-resampling repo](https://uk.mathworks.com/matlabcentral/fileexchange/52741-statistics-resampling/) by necessary updating of the GitHub integration would be by having my membership at gnu-octave being temporarily assigned as owner for me to complete the login to MathWorks with my account details... but I imagine that is not a satisfactory solution for you folks.

**Comment by mmuetzel** [comment]
I made you an owner of the organization.
Does that help?

**Comment by acp29** [comment]
Hi @mmuetzel, yup that worked thanks. 😊 

There were some other issues persisting with the integration but not related to the issue above - I have resolved those (mostly) through contact with Mathworks support
